#!/bin/bash

set -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
export GOPATH=$DIR
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOPATH/bin

go build -v -o ./my_app ./src/example.com/cmd/app/main.go
